name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "boards/**"
      - "config/**"
      - "zephyr/**"
      - "build.yaml"
      - ".github/workflows/**"
    tags-ignore:
      - "*"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
